const assert = require('assert')
const fs = require('fs')
const path = require('path')

const root = path.resolve(__dirname, '..', '..')
const mini = path.join(root, 'campus_treehole')
const order = fs.readFileSync(path.join(mini, 'packageExpress/pages/order/order.wxml'), 'utf8')
const orderJs = fs.readFileSync(path.join(mini, 'packageExpress/pages/order/order.js'), 'utf8')
const staff = fs.readFileSync(path.join(mini, 'packageExpress/pages/staff-orders/staff-orders.wxml'), 'utf8')
const staffJs = fs.readFileSync(path.join(mini, 'packageExpress/pages/staff-orders/staff-orders.js'), 'utf8')
const detail = fs.readFileSync(path.join(mini, 'packageExpress/pages/detail/detail.wxml'), 'utf8')
const orders = fs.readFileSync(path.join(mini, 'packageExpress/pages/orders/orders.wxml'), 'utf8')
const homeJs = fs.readFileSync(path.join(mini, 'pages/index/index.js'), 'utf8')
const home = fs.readFileSync(path.join(mini, 'pages/index/index.wxml'), 'utf8')

assert.ok(order.includes('pickupGroups') && order.includes('addPickupPoint') && order.includes('addPickupCode'), 'Order renders grouped multi-pickup inputs')
assert.ok(order.includes('showProfileSheet') && order.includes('visibleProfiles') && order.includes('deliveryForm') && order.includes('inline-profile-editor'), 'Order keeps profile switching and first-time delivery inline')
assert.ok(orderJs.includes('pickupItems') && orderJs.includes('deliveryData') && orderJs.includes('saveDeliveryProfile') && orderJs.includes('quoteTimer'), 'Order sends multi-pickup and inline delivery data with debounced quote')
assert.ok(orderJs.includes('onImportScreenshots') && orderJs.includes('recognizeExpressScreenshots') && orderJs.includes('confirmImport') && orderJs.includes('retryImportScreenshots') && orderJs.includes('closeImportSheet'), 'Order wires screenshot OCR import through editable confirmation, cancel and retry')
assert.ok(order.includes('截图一键导入') && order.includes('showImportSheet') && order.includes('全部导入到下单页'), 'Order UI exposes screenshot import and confirmation sheet')
assert.ok(!orderJs.includes("createExpressOrder', { requestId") && !orderJs.includes("createExpressOrder', { imageFileIds"), 'Screenshot import does not auto-create an order')
assert.ok(!orderJs.includes("wx.navigateTo({ url: `/packageExpress/pages/delivery-profiles"), 'Checkout does not require a profile-management navigation')
assert.ok(staff.includes('配送模式') && staff.includes('取件模式') && staff.includes('pickupGroups') && staff.includes('deliveryGroups'), 'Staff UI has pickup and delivery modes')
assert.ok(staffJs.includes('workMode') && staffJs.includes('selectedPickupItemIds') && staffJs.includes('allItemsSelected'), 'Staff selection is item-based and blocks partial order delivery')
assert.ok(detail.includes('pickupItems') && detail.includes('取件码'), 'Order detail renders each pickup item')
assert.ok(orders.includes('pickupPointSummary') && orders.includes('totalPackageCount') && !orders.includes('pickupCode'), 'My orders show aggregate pickup summary without exposing all codes')
assert.ok(homeJs.includes('totalPackageCount') && homeJs.includes('pickupPointCount') && home.includes('activeOrder.summary'), 'Home summary uses aggregate package and pickup-point counts')
assert.ok(fs.existsSync(path.join(root, 'scripts/migrations/migrate-express-pickup-items.js')), 'Pickup item migration script exists')
console.log('PASS Express 3.7 UI contract: inline checkout, grouped pickup codes, staff modes, aggregate home summary')
