const assert = require('assert')
const fs = require('fs')
const path = require('path')
const root = path.resolve(__dirname, '..', '..')
const mini = path.join(root, 'campus_treehole')
const app = JSON.parse(fs.readFileSync(path.join(mini, 'app.json'), 'utf8'))
const express = app.subpackages.find((item) => item.root === 'packageExpress')
assert.ok(express && express.pages.length === 11)
for (const page of express.pages) {
  const base = path.join(mini, 'packageExpress', page)
  for (const ext of ['js', 'json', 'wxml', 'wxss']) assert.ok(fs.existsSync(`${base}.${ext}`), `${page}.${ext} exists`)
  const json = JSON.parse(fs.readFileSync(`${base}.json`, 'utf8'))
  assert.ok(json.usingComponents && json.usingComponents['campus-page-header'])
}
const mine = fs.readFileSync(path.join(mini, 'pages/mine/mine.wxml'), 'utf8')
const index = fs.readFileSync(path.join(mini, 'pages/index/index.wxml'), 'utf8')
assert.ok(mine.includes('staffCapabilities.isStaff') && mine.includes('staffCapabilities.isOwner'))
assert.ok(index.includes('onOpenExpress') && index.includes('快递代拿'))
assert.ok(index.includes('express-home-cta') && index.includes('express-home-price') && index.includes('parcel-box'), 'Express home card is a large, salient hero')
assert.ok(index.includes('express-home-closed') && index.includes('今日暂停接单'), 'Home hero does not promise ordering while closed')
assert.ok(index.includes('服务尚未配置') && index.includes('服务状态加载失败'), 'Home hero distinguishes unconfigured and load error states')
const order = fs.readFileSync(path.join(mini, 'packageExpress/pages/order/order.wxml'), 'utf8')
const orderJs = fs.readFileSync(path.join(mini, 'packageExpress/pages/order/order.js'), 'utf8')
assert.ok(order.includes('服务尚未配置') && order.includes('服务配置加载失败') && order.includes('selectedProfile') && orderJs.includes('clientRequestId'), 'Order form distinguishes service configuration states')
assert.ok(order.includes('selected-profile') && orderJs.includes('deliveryProfileId'), 'Order form selects an account-level delivery profile')
assert.ok(!orderJs.includes('createExpressOrder\', { ...this.data.form'), 'New order submission does not trust client address fields')
assert.ok(orderJs.includes('prefillCachedDelivery') && orderJs.includes('deliveryData'), 'Legacy address cache is used only as an inline fallback')
assert.ok(mine.includes('常用配送信息') && mine.includes('data-page="expressProfiles"'), 'Mine exposes account-level delivery profile management')
const profileList = fs.readFileSync(path.join(mini, 'packageExpress/pages/delivery-profiles/delivery-profiles.wxml'), 'utf8')
const profileEdit = fs.readFileSync(path.join(mini, 'packageExpress/pages/delivery-profile-edit/delivery-profile-edit.wxml'), 'utf8')
assert.ok(profileList.includes('给自己') && profileList.includes('帮别人') && profileList.includes('新增配送信息'))
assert.ok(profileEdit.includes('收件人姓名') && profileEdit.includes('设为默认配送信息'))
assert.ok(!mine.includes('isStaff === true'), 'Mine does not trust a client-only staff flag')
for (const page of express.pages.filter((page) => page.includes('/staff-'))) {
  const js = fs.readFileSync(path.join(mini, 'packageExpress', `${page}.js`), 'utf8')
  assert.ok(js.includes('getMyStaffCapabilities'), `${page} rechecks staff capabilities`)
}
assert.ok(!fs.readdirSync(path.join(mini, 'packageExpress'), { withFileTypes: true }).some((entry) => entry.isDirectory() && entry.name === 'legacy'))
console.log('PASS Express UI: package routes, Mine capability-gated workbench, student home entry')
