const assert = require('assert')
const fs = require('fs')
const path = require('path')
const root = path.resolve(__dirname, '..', '..')
const source = fs.readFileSync(path.join(root, 'campus_treehole/cloudfunctions/dbOperations/modules/express.js'), 'utf8')
const adapter = fs.readFileSync(path.join(root, 'campus_treehole/cloudfunctions/dbOperations/modules/payment-adapter.js'), 'utf8')
assert.ok(source.includes('clientRequestId'))
assert.ok(source.includes('deliveryCampusNameSnapshot'))
assert.ok(source.includes('paymentStatus === EXPRESS_PAYMENT_STATUS.PAID'))
assert.ok(!source.includes('openid:'))
assert.ok(adapter.includes('createPayment') && adapter.includes('queryPayment') && adapter.includes('handlePaymentNotification'))
console.log('PASS Express security contract: server identity, snapshots, paid-only staff and no OpenID response')
