const assert=require('assert');const {fixture}=require('../helpers/heart-fixture');const createSafety=require('../../campus_treehole/cloudfunctions/dbOperations/modules/safety')
;(async()=>{const f=await fixture(),a=await f.add('a','male'),b=await f.add('b');f.db.serverDate=()=>Date.now()
const safety=createSafety({db:f.db,_:f.db.command,helpers:{getUserForAction:async id=>f.users[id],isCollectionNotExistError:()=>false,isUserBlocksUnavailableError:()=>false}})
assert.equal((await safety.reportContent('a',{targetId:b.userId,targetType:'heart_profile',reason:'资料违规'})).code,0)
assert.equal((await safety.reportContent('a',{targetId:b.userId,targetType:'heart_photo',photoIndex:0,photoFileId:b.profile.photos[0],reason:'图片违规'})).code,0)
assert.notEqual((await safety.reportContent('a',{targetId:b.userId,targetType:'heart_photo',photoIndex:0,photoFileId:'cloud://other/heart/nope.jpg',reason:'图片违规'})).code,0)
assert.equal((await safety.toggleUserBlock('a','b')).data.blocked,true)
assert.equal((await f.heart.getHeartDiscover('a')).data.rows.length,0)
assert.notEqual((await f.heart.likeHeartProfile('a',{targetUserId:b.userId})).code,0)
assert.equal((await f.heart.drawFateCard('a')).data.empty,true)
console.log('PASS Heart safety: reused report types, reason validation, block fence excludes discover/like/fate')})().catch(e=>{console.error(e);process.exitCode=1})
