const assert=require('assert');const {fixture}=require('../helpers/heart-fixture')
;(async()=>{const f=await fixture(),a=await f.add('a','male'),b=await f.add('b')
assert.notEqual((await f.heart.startHeartChat('a',{targetUserId:b.userId})).code,0)
assert.equal((await f.heart.likeHeartProfile('a',{targetUserId:b.userId})).data.status,'WAITING')
await Promise.all([f.heart.likeHeartProfile('b',{targetUserId:a.userId}),f.heart.likeHeartProfile('a',{targetUserId:b.userId})])
assert.equal(Object.keys(f.db.dump().heart_matches).length,1);assert.equal(Object.keys(f.db.dump().heart_likes).length,2)
assert.equal((await f.heart.startHeartChat('a',{targetUserId:b.userId})).code,0)
f.blocked.add('a:b');assert.notEqual((await f.heart.likeHeartProfile('a',{targetUserId:b.userId})).code,0);assert.equal((await f.heart.getHeartMatches('a')).data.length,0)
console.log('PASS Heart like: waiting, idempotency, mutual match, chat gate, block')})().catch(e=>{console.error(e);process.exitCode=1})
